var http = require('http');
const BufferList = require('bl');

var url = process.argv[2];
var bufferList = new BufferList();

http.get(url, function(responseStream) {
	responseStream.on("data", function(data) { // data is a single buffer, generated by the stream with the data event
		bufferList.append(data.toString())
	})
	responseStream.on("end", function(data) { // end emitted when the stream is done (flushed, closed)
		console.log(bufferList.length);
		console.log(bufferList.toString());
	})
});
