var http = require('http');

var url = process.argv[2];
http.get(url, function(responseStream) {
	responseStream.on("data", function(data) { // data is a single buffer, generated by the stream with the data event
		console.log(data.toString());
	})
});